options{
	STATIC = false;
}
PARSER_BEGIN(Adder)

import java.io.*;

class Adder{
	static public void mian(String[] args){
		for(String arg:args){
			try{
				System.out.println(evaluate(arg));
			}
			catch(ParseException ex){
				System.err.println(ex.getMessage());
			}
		}
	}
}
PARSER_END(Adder)

SKIP:{<[" ","\t","\r","\n"]>}

TOKEN:{
	< INTERGER: (["0"-"9"])+ >
}

long expr():
{
	Token x, y;
}
{
	x=<INTERGER> "+" y=<INTERGER> <EOF>
		{
			return Long.parseLong(x.image) + Long.parseLong(y.image);
		}
}